// packages/angular/src/lib/components/layout/row/row.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { UniBoxComponent } from '../box/box.component';
import type { OptionalDisplay, OptionalFlexDirection } from '@uni-design-system/uni-core';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: '[uni-row-layout], [row-layout]',
  template: `<ng-content></ng-content>`,
})
export class UniRowComponent extends UniBoxComponent {
  override display = input<OptionalDisplay>('flex');
  override flexDirection = input<OptionalFlexDirection>('row');
  /**
   * Defaults to `fit-content` (guards content collapse). Set `[minWidth]="0"`
   * when the row must shrink inside a constrained flex parent (scroll or
   * text truncation containment).
   */
  override minWidth = input<number | string | undefined>('fit-content');

  constructor() {
    super();
  }
}

// packages/react/src/components/layout/row/row.component.tsx
import React, { forwardRef, type ElementType } from 'react';

import type { PolymorphicComponent } from '../../../core/polymorphic';
import { Box, type BoxOwnProps, type BoxProps } from '../box';

export type RowProps<E extends ElementType = 'div'> = BoxProps<E>;

/**
 * A horizontal Box: `display: flex` in a row.
 *
 * `minWidth` defaults to `fit-content` (guards content collapse). Set
 * `minWidth={0}` when the row must shrink inside a constrained flex parent
 * (scroll or text-truncation containment).
 */
export const Row = forwardRef<Element, BoxOwnProps>(function Row(props, ref) {
  return (
    <Box
      display="flex"
      flexDirection="row"
      minWidth="fit-content"
      {...(props as BoxProps)}
      ref={ref}
    />
  );
}) as PolymorphicComponent<BoxOwnProps>;

Row.displayName = 'Row';
