// packages/angular/src/lib/components/layout/stack/stack.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { UniBoxComponent } from '../box/box.component';
import type { OptionalDisplay, OptionalFlexDirection } from '@uni-design-system/uni-core';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: '[uni-stack-layout], [stack-layout]',
  template: `<ng-content></ng-content>`,
})
export class UniStackComponent extends UniBoxComponent {
  override display = input<OptionalDisplay>('flex');
  override flexDirection = input<OptionalFlexDirection>('column');
  /**
   * Defaults to `fit-content` (guards content collapse). Set `[minHeight]="0"`
   * when the stack must shrink inside a constrained flex parent (scroll
   * containment).
   */
  override minHeight = input<number | string | undefined>('fit-content');

  constructor() {
    super();
  }
}

// packages/react/src/components/layout/stack/stack.component.tsx
import React, { forwardRef, type ElementType } from 'react';

import type { PolymorphicComponent } from '../../../core/polymorphic';
import { Box, type BoxOwnProps, type BoxProps } from '../box';

export type StackProps<E extends ElementType = 'div'> = BoxProps<E>;

/**
 * A vertical Box: `display: flex` in a column.
 *
 * `minHeight` defaults to `fit-content` (guards content collapse). Set
 * `minHeight={0}` when the stack must shrink inside a constrained flex parent
 * (scroll containment).
 */
export const Stack = forwardRef<Element, BoxOwnProps>(function Stack(props, ref) {
  return (
    <Box
      display="flex"
      flexDirection="column"
      minHeight="fit-content"
      {...(props as BoxProps)}
      ref={ref}
    />
  );
}) as PolymorphicComponent<BoxOwnProps>;

Stack.displayName = 'Stack';
